version: "3.7"

services:

  influxdb:
    container_name: influxdb
    build: ./influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'influxdb/env.influxdb'
    volumes:
      - /var/influxdb/data:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)

  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - mycodo_var:/var/mycodo
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

  daemon:
    container_name: daemon
    image: app
    restart: always
    volumes:
      - mycodo_var:/var/mycodo
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)
    privileged: true
    ports:
      - "18813:18813"
    command: bash -c "PYTHONPATH=/home/mycodo python mycodo_daemon.py"
    depends_on:
      - flask
      - influxdb

  flask:
    container_name: flask
    image: app
    restart: always
    build: .
    volumes:
      - mycodo_var:/var/mycodo
      - /etc/localtime:/etc/localtime:ro  # Use timezone of the host (read-only)
    privileged: true
    command: gunicorn --workers 1 --bind unix:/var/mycodo/mycodoflask.sock start_flask_ui:app
    depends_on:
      - influxdb

volumes:
  mycodo_var:
